name: Zola Deploy Action

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write
  

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shalzz/zola-deploy-action@v0.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          path: '.'
      - uses: actions/deploy-pages@v4
